# ~/.config/starship.toml

[aws]
disabled = true

[directory]
truncate_to_repo = true

[directory.substitutions]
"~/github" = "github.com"

[git_branch]
symbol = " "

[nodejs]
disabled = true
format = "using [$symbol$version]($style) "

[package]
disabled = true
format = "[$symbol$version]($style) "
symbol = " "
